[package]
name = "taffy"
version = "0.3.11"
authors = [
    "Alice Cecile <alice.i.cecile@gmail.com>",
    "Johnathan Kelley <jkelleyrtp@gmail.com>",
]
edition = "2021"
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "A flexible UI layout library "
repository = "https://github.com/DioxusLabs/taffy"
keywords = ["cross-platform", "layout", "flexbox", "css-grid", "grid"]
categories = ["gui"]
license = "MIT"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }
slotmap = { version = "1.0.6", optional = true }
grid = { version = "0.9.0", optional = true }

[features]
default = ["std", "flexbox", "grid", "taffy_tree"]
flexbox = []
grid = ["alloc", "dep:grid"]
alloc = []
std = ["num-traits/std"]
serde = ["dep:serde"]
debug = []
profile = []
taffy_tree = ["dep:slotmap"]

[dev-dependencies]
serde_json = "1.0.93"

# Enable default features for tests and examples
taffy = { path = "." }

[profile.release]
lto = true
panic = 'abort'

[[bench]]
name = "dummy_benchmark"
path = "benches/dummy_benchmark.rs"
harness = false

[workspace]
members = ["scripts/gentest", "scripts/format-fixtures", "scripts/import-yoga-tests", "benches"]
